### ISSUE TITLE
Inconsistant MacroF1 scores in the paper

### ISSUE THREAD

**Issue by thcheung** [JohnNLP/PhemePlus#1]
The table 5 in the paper shows MacroF1 scores of different methods. However, the calculation is different in some of the rows.

For example, the results of BERT with Rumour + Ev. obtains MacroF1 of 0.345, which is calculated by macro average of the three classes, i.e. (0.221 + 0.549 + 0.265) / 3= 0.345,

Differently, the results of NLT-SAN obtains Macro F1 of 0.405, which is calculated by macro average of the five events, i.e. (0.354 + 0.256 + 0.365 + 0.591 + 0.458 ) / 5  = 0.405.

It seems that the results of average of the five events is different from the average of the three classes

May I know which macro-F1 score that you were trying to calculate, so that we may update the results in my publications when doing comparison?

**Comment by JohnNLP** [comment]
Hi, sorry for the delayed response. It seems as though the co-author made an error in that row (of unknown form) which nobody caught - it should be the average of the 3 classes T/F/U. I would suggest not to use the NLI-SAN result.
